### ISSUE TITLE
Does not work on Mac

### ISSUE THREAD

**Issue by CMeza99** [kobus-v-schoor/dotgit#23] opened 2019-04-23 00:42 UTC
```
$ ~/dotgit/bin/dotgit init
readlink: illegal option -- f
usage: readlink [-n] [file ...]
~/dotgit/bin/dotgit: line 19: ./dotgit_headers/help: No such file or directory
~/dotgit/bin/dotgit: line 21: ./dotgit_headers/repo: No such file or directory
~/dotgit/bin/dotgit: line 23: ./dotgit_headers/update: No such file or directory
~/dotgit/bin/dotgit: line 25: ./dotgit_headers/restore: No such file or directory
~/dotgit/bin/dotgit: line 27: ./dotgit_headers/clean: No such file or directory
~/dotgit/bin/dotgit: line 29: ./dotgit_headers/security: No such file or directory
~/dotgit/bin/dotgit: line 31: ./dotgit_headers/diff: No such file or directory
~/dotgit/bin/dotgit: line 34: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
~/dotgit/bin/dotgit: line 56: EB-Mac.local: syntax error: invalid arithmetic operator (error token is ".local")
~/dotgit/bin/dotgit: line 60: verecho: command not found
~/dotgit/bin/dotgit: line 96: init: command not found
```

**Comment by ddddanil** [comment] 2020-08-29 20:12
Hey, it's an old issue but I think I should post a small fix for everyone peeking in here.

The issue is that mac utils aren't the same as GNU utils, and the standard bash version here is 3.2. To get around that you can `brew install coreutils bash`
After that you can get dotgit working just by editing these two lines in the script
1) Point to the new version of bash, line 1
~~`#! /bin/bash`~~ --> `#! /usr/local/bin/bash`
2) Use GNU utils, line 10
~~`declare -r DG_H=$(dirname "$(readlink -f "$0")")/dotgit_headers # Headers DIR`~~
 v 
`declare -r DG_H=$(dirname "$(greadlink -f "$0")")/dotgit_headers # Headers DIR`

You can probably fix these issues by adding some if-s, or even better by making a Homebrew package with all the appropriate dependencies.

**Comment by kobus-v-schoor** [comment] 2020-08-29 21:38
Hey @ddddanil, thanks for the comment - I've actually been working on a python version of dotigit (visible in the python branch of this repo) in an effort to specifically make it more cross-platform. Hopefully I will be able to make a release soon

**Comment by kobus-v-schoor** [comment] 2020-09-04 17:26
New rewrite using Python release which should fix issues on MacOS, closing

**Closed by kobus-v-schoor** 2020-09-04 17:26 UTC
